version: "3.8"

services:
  # 1. FastAPI Backend Engine (Port 8000 public open කරයි)
  crop-api-service:
    image: kosala2002/crop-backend:latest
    container_name: crop-api
    ports:
      - "8000:8000"  # 👈 මින් පිටත සිටින අයට 8000 පෝට් එක හරහා API එකට සෘජුව කතා කළ හැක
    restart: unless-stopped
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000

  # 2. Production React Frontend (Port 80 public open කරයි)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crop-frontend
    ports:
      - "80:80"      # 👈 බ්‍රවුසර් එකේ IP එක විතරක් ගැසූ විට (Default Port 80) කෙලින්ම UI එක ලෝඩ් වේ
    restart: unless-stopped
    depends_on:
      - crop-api-service